####
# This Dockerfile is used in order to build a container that runs the Vert.x application in JVM mode
#
# Before building the container image run:
#
# ./mvnw package
#
# Then, build the image with:
#
# docker build -f src/main/docker/Dockerfile.jvm -t vertx/vertx-test-jvm .
#
# Then run the container using:
#
# docker run -i --rm -p 8080:8080 vertx/vertx-test-jvm
#
# The application listens on port 8080. Set the HTTP_PORT environment variable to change it:
#
# docker run -i --rm -p 9090:9090 -e HTTP_PORT=9090 vertx/vertx-test-jvm
#
# If you want to include the debug port into your docker image
# you will have to expose the debug port (default 5005 being the default) like this :  EXPOSE 8080 5005.
# Additionally you will have to append the agent options to JAVA_OPTS when running the container:
#
# docker run -i --rm -p 8080:8080 -p 5005:5005 \
#   -e JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" \
#   vertx/vertx-test-jvm
#
# You can find more information about the UBI base runtime images and their configuration here:
# https://rh-openjdk.github.io/redhat-openjdk-containers/
###
FROM registry.access.redhat.com/ubi9/openjdk-25-runtime:1.24

ENV LANGUAGE='en_US:en'

COPY --chown=185 target/*-runner.jar /deployments/application.jar

EXPOSE 8080
USER 185
ENV JAVA_OPTS=""

ENTRYPOINT [ "sh", "-c", "exec java $JAVA_OPTS -jar /deployments/application.jar" ]
